### ISSUE TITLE
legal markdown reader/parser

### ISSUE THREAD

**Issue by loeffel-io** [makeless/makeless-ui#48]

**Comment by loeffelr** [comment]
check if bspw. imprint.md vorhanden
wenn vorhanden, erstelle Imprint.vue page
Imprint.vue liest dann inhalt aus imprint.md als markdown reader

**Comment by loeffelr** [comment]
Imprint.vue:
requiresMarkdown: "imprint" --> security funktion
wenn imprint vorhanden, dann render
