### ISSUE TITLE
Site is reloading on resizing

### ISSUE THREAD

**Issue by loeffel-io** [makeless/makeless-ui#97]
Could be a chrome problem

![2020-11-04 12 30 04](https://user-images.githubusercontent.com/12670730/98106510-b0349e00-1e99-11eb-9d44-2ee0969ff310.gif)

**Comment by loeffelr** [comment]
cannot reproduce on chrome, firefox and safari

**Comment by loeffel-io** [comment]
teste das später im inkognito

**Comment by loeffel-io** [comment]
depends on google chrome plugin ..
